theme: jekyll-theme-midnight
title: Welcome to the course webpage for EE524 (Machine Learning Laboratory) !!!
description: This is the course webpage for EE524. All announcements regarding tutorials, assignments, resources, deadlines will be posted here.
